/* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0. If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/. */

const { Cc, Ci } = require("chrome");

let windowMediator = exports.windowMediator = Cc["@mozilla.org/appshell/window-mediator;1"].getService(Ci.nsIWindowMediator);

let prompterService = exports.prompterService = Cc["@mozilla.org/embedcomp/prompt-service;1"].getService(Ci.nsIPromptService);

let keys = exports.keys = Ci.nsIDOMKeyEvent;

var _ = require("sdk/l10n").get;

let unusableKeys = exports.unusableKeys = [
"tabGroups-key-tabView",
"tabGroups-key-nextGroup",
"tabGroups-key-previousGroup",
"key_hideThisAppCmdMac",
"key_hideOtherAppsCmdMac",


];

const domKeys = exports.domKeys = {
	"virtual_keys":{
		"VK_CANCEL":{keyCode:3,charCode:0},
		"VK_HELP":{keyCode:5,charCode:0},
		"VK_BACK":{keyCode:8,charCode:8},
		"VK_BACK_SPACE":{keyCode:8,charCode:8},
		"VK_TAB":{keyCode:9,charCode:9,key:"⇥"},
		"VK_CLEAR":{keyCode:12,charCode:0},
		"VK_RETURN":{keyCode:13,charCode:13},
		"VK_SHIFT":{keyCode:16,charCode:0},
		"VK_CONTROL":{keyCode:17,charCode:0},
		"VK_ALT":{keyCode:18,charCode:0},
		"VK_PAUSE":{keyCode:19,charCode:0},
		"VK_CAPS_LOCK":{keyCode:20,charCode:0},
		"VK_KANA":{keyCode:21,charCode:0},
		"VK_HANGUL":{keyCode:21,charCode:0},
		"VK_EISU":{keyCode:22,charCode:0},
		"VK_JUNJA":{keyCode:23,charCode:0},
		"VK_FINAL":{keyCode:24,charCode:0},
		"VK_HANJA":{keyCode:25,charCode:0},
		"VK_KANJI":{keyCode:25,charCode:0},
		"VK_ESCAPE":{keyCode:27,charCode:27},
		"VK_CONVERT":{keyCode:28,charCode:0},
		"VK_NONCONVERT":{keyCode:29,charCode:0},
		"VK_ACCEPT":{keyCode:30,charCode:0},
		"VK_MODECHANGE":{keyCode:31,charCode:0},
		"VK_SPACE":{keyCode:32,charCode:32},
		"VK_PAGE_UP":{keyCode:33,charCode:0},
		"VK_PAGE_DOWN":{keyCode:34,charCode:0},
		"VK_END":{keyCode:35,charCode:0},
		"VK_HOME":{keyCode:36,charCode:0},
		"VK_LEFT":{keyCode:37,charCode:0,key:"←"},
		"VK_UP":{keyCode:38,charCode:0,key:"↑"},
		"VK_RIGHT":{keyCode:39,charCode:0,key:"→"},
		"VK_DOWN":{keyCode:40,charCode:0,key:"↓"},
		"VK_SELECT":{keyCode:41,charCode:0},
		"VK_PRINT":{keyCode:42,charCode:0},
		"VK_EXECUTE":{keyCode:43,charCode:0},
		"VK_PRINTSCREEN":{keyCode:44,charCode:0},
		"VK_INSERT":{keyCode:45,charCode:0},
		"VK_DELETE":{keyCode:46,charCode:0},
		"VK_0":{keyCode:48,charCode:48,key:"0"},
		"VK_1":{keyCode:49,charCode:49,key:"1"},
		"VK_2":{keyCode:50,charCode:50,key:"2"},
		"VK_3":{keyCode:51,charCode:51,key:"3"},
		"VK_4":{keyCode:52,charCode:52,key:"4"},
		"VK_5":{keyCode:53,charCode:53,key:"5"},
		"VK_6":{keyCode:54,charCode:54,key:"6"},
		"VK_7":{keyCode:55,charCode:55,key:"7"},
		"VK_8":{keyCode:56,charCode:56,key:"8"},
		"VK_9":{keyCode:57,charCode:59,key:"9"},
		"VK_COLON":{keyCode:58,charCode:58,key:":"},
		"VK_SEMICOLON":{keyCode:59,charCode:59,key:";"},
		"VK_LESS_THAN":{keyCode:60,charCode:60,key:"<"},
		"VK_EQUALS":{keyCode:61,charCode:61,key:"="},
		"VK_GREATER_THAN":{keyCode:62,charCode:62,key:">"},
		"VK_QUESTION_MARK":{keyCode:63,charCode:63,key:"?"},
		"VK_AT":{keyCode:64,charCode:64,key:"@"},
		"VK_A":{keyCode:65,charCode:65,key:"A"},
		"VK_B":{keyCode:66,charCode:66,key:"B"},
		"VK_C":{keyCode:67,charCode:67,key:"C"},
		"VK_D":{keyCode:68,charCode:68,key:"D"},
		"VK_E":{keyCode:69,charCode:69,key:"E"},
		"VK_F":{keyCode:70,charCode:70,key:"F"},
		"VK_G":{keyCode:71,charCode:71,key:"G"},
		"VK_H":{keyCode:72,charCode:72,key:"H"},
		"VK_I":{keyCode:73,charCode:73,key:"I"},
		"VK_J":{keyCode:74,charCode:74,key:"J"},
		"VK_K":{keyCode:75,charCode:75,key:"K"},
		"VK_L":{keyCode:76,charCode:76,key:"L"},
		"VK_M":{keyCode:77,charCode:77,key:"M"},
		"VK_N":{keyCode:78,charCode:78,key:"N"},
		"VK_O":{keyCode:79,charCode:79,key:"O"},
		"VK_P":{keyCode:80,charCode:80,key:"P"},
		"VK_Q":{keyCode:81,charCode:81,key:"Q"},
		"VK_R":{keyCode:82,charCode:82,key:"R"},
		"VK_S":{keyCode:83,charCode:83,key:"S"},
		"VK_T":{keyCode:84,charCode:84,key:"T"},
		"VK_U":{keyCode:85,charCode:85,key:"U"},
		"VK_V":{keyCode:86,charCode:86,key:"V"},
		"VK_W":{keyCode:87,charCode:87,key:"W"},
		"VK_X":{keyCode:88,charCode:88,key:"X"},
		"VK_Y":{keyCode:89,charCode:89,key:"Y"},
		"VK_Z":{keyCode:90,charCode:90,key:"Z"},
		"VK_WIN":{keyCode:91,charCode:0},
		"VK_CONTEXT_MENU":{keyCode:93,charCode:0},
		"VK_SLEEP":{keyCode:95,charCode:0},
		"VK_NUMPAD0":{keyCode:96,charCode:48},
		"VK_NUMPAD1":{keyCode:97,charCode:49},
		"VK_NUMPAD2":{keyCode:98,charCode:50},
		"VK_NUMPAD3":{keyCode:99,charCode:51},
		"VK_NUMPAD4":{keyCode:100,charCode:52},
		"VK_NUMPAD5":{keyCode:101,charCode:53},
		"VK_NUMPAD6":{keyCode:102,charCode:54},
		"VK_NUMPAD7":{keyCode:103,charCode:55},
		"VK_NUMPAD8":{keyCode:104,charCode:56},
		"VK_NUMPAD9":{keyCode:105,charCode:57},
		"VK_MULTIPLY":{keyCode:106,charCode:42},
		"VK_ADD":{keyCode:107,charCode:43},
		"VK_SEPARATOR":{keyCode:108,charCode:44},
		"VK_SUBTRACT":{keyCode:109,charCode:45},
		"VK_DECIMAL":{keyCode:110,charCode:46},
		"VK_DIVIDE":{keyCode:111,charCode:47},
		"VK_F1":{keyCode:112,charCode:0,key:"F1"},
		"VK_F2":{keyCode:113,charCode:0,key:"F2"},
		"VK_F3":{keyCode:114,charCode:0,key:"F3"},
		"VK_F4":{keyCode:115,charCode:0,key:"F4"},
		"VK_F5":{keyCode:116,charCode:0,key:"F5"},
		"VK_F6":{keyCode:117,charCode:0,key:"F6"},
		"VK_F7":{keyCode:118,charCode:0,key:"F7"},
		"VK_F8":{keyCode:119,charCode:0,key:"F8"},
		"VK_F9":{keyCode:120,charCode:0,key:"F9"},
		"VK_F10":{keyCode:121,charCode:0,key:"F10"},
		"VK_F11":{keyCode:122,charCode:0,key:"F11"},
		"VK_F12":{keyCode:123,charCode:0,key:"F12"},
		"VK_F13":{keyCode:124,charCode:0,key:"F13"},
		"VK_F14":{keyCode:125,charCode:0,key:"F14"},
		"VK_F15":{keyCode:126,charCode:0,key:"F15"},
		"VK_F16":{keyCode:127,charCode:0,key:"F16"},
		"VK_F17":{keyCode:128,charCode:0,key:"F17"},
		"VK_F18":{keyCode:129,charCode:0,key:"F18"},
		"VK_F19":{keyCode:130,charCode:0,key:"F19"},
		"VK_F20":{keyCode:131,charCode:0,key:"F20"},
		"VK_F21":{keyCode:132,charCode:0,key:"F21"},
		"VK_F22":{keyCode:133,charCode:0,key:"F22"},
		"VK_F23":{keyCode:134,charCode:0,key:"F23"},
		"VK_F24":{keyCode:135,charCode:0,key:"F24"},
		"VK_NUM_LOCK":{keyCode:144,charCode:0},
		"VK_SCROLL_LOCK":{keyCode:145,charCode:0},
		"VK_WIN_OEM_FJ_JISHO":{keyCode:146,charCode:0},
		"VK_WIN_OEM_FJ_MASSHOU":{keyCode:147,charCode:0},
		"VK_WIN_OEM_FJ_TOUROKU":{keyCode:148,charCode:0},
		"VK_WIN_OEM_FJ_LOYA":{keyCode:149,charCode:0},
		"VK_WIN_OEM_FJ_ROYA":{keyCode:150,charCode:0},
		"VK_CIRCUMFLEX":{keyCode:160,charCode:94,key:"^"},
		"VK_EXCLAMATION":{keyCode:161,charCode:33,key:"!"},
		"VK_DOUBLE_QUOTE":{keyCode:162,charCode:34,key:"\""},
		"VK_HASH":{keyCode:163,charCode:35,key:"#"},
		"VK_DOLLAR":{keyCode:164,charCode:36,key:"$"},
		"VK_PERCENT":{keyCode:165,charCode:37,key:"%"},
		"VK_AMPERSAND":{keyCode:166,charCode:38,key:"&"},
		"VK_UNDERSCORE":{keyCode:167,charCode:95,key:"_"},
		"VK_OPEN_PAREN":{keyCode:168,charCode:40,key:"("},
		"VK_CLOSE_PAREN":{keyCode:169,charCode:41,key:")"},
		"VK_ASTERISK":{keyCode:170,charCode:42,key:"*"},
		"VK_PLUS":{keyCode:171,charCode:43,key:"+"},
		"VK_PIPE":{keyCode:172,charCode:124,key:"|"},
		"VK_HYPHEN_MINUS":{keyCode:173,charCode:45,key:"-"},
		"VK_OPEN_CURLY_BRACKET":{keyCode:174,charCode:123,key:"{"},
		"VK_CLOSE_CURLY_BRACKET":{keyCode:175,charCode:125,key:"}"},
		"VK_TILDE":{keyCode:176,charCode:126,key:"~"},
		"VK_VOLUME_MUTE":{keyCode:181,charCode:0},
		"VK_VOLUME_DOWN":{keyCode:182,charCode:0},
		"VK_VOLUME_UP":{keyCode:183,charCode:0},
		"VK_COMMA":{keyCode:188,charCode:44,key:","},
		"VK_PERIOD":{keyCode:190,charCode:46,key:"."},
		"VK_SLASH":{keyCode:191,charCode:47,key:"/"},
		"VK_BACK_QUOTE":{keyCode:192,charCode:96,key:"`"},
		"VK_OPEN_BRACKET":{keyCode:219,charCode:91,key:"["},
		"VK_BACK_SLASH":{keyCode:220,charCode:92,key:"\\"},
		"VK_CLOSE_BRACKET":{keyCode:221,charCode:93,key:"]"},
		"VK_QUOTE":{keyCode:222,charCode:39,key:"'"},
		"VK_META":{keyCode:224,charCode:0},
		"VK_ALTGR":{keyCode:225,charCode:0},
		"VK_WIN_ICO_HELP":{keyCode:227,charCode:0},
		"VK_WIN_ICO_00":{keyCode:228,charCode:0},
		"VK_WIN_ICO_CLEAR":{keyCode:230,charCode:0},
		"VK_WIN_OEM_RESET":{keyCode:233,charCode:0},
		"VK_WIN_OEM_JUMP":{keyCode:234,charCode:0},
		"VK_WIN_OEM_PA1":{keyCode:235,charCode:0},
		"VK_WIN_OEM_PA2":{keyCode:236,charCode:0},
		"VK_WIN_OEM_PA3":{keyCode:237,charCode:0},
		"VK_WIN_OEM_WSCTRL":{keyCode:238,charCode:0},
		"VK_WIN_OEM_CUSEL":{keyCode:239,charCode:0},
		"VK_WIN_OEM_ATTN":{keyCode:240,charCode:0},
		"VK_WIN_OEM_FINISH":{keyCode:241,charCode:0},
		"VK_WIN_OEM_COPY":{keyCode:242,charCode:0},
		"VK_WIN_OEM_AUTO":{keyCode:243,charCode:0},
		"VK_WIN_OEM_ENLW":{keyCode:244,charCode:0},
		"VK_WIN_OEM_BACKTAB":{keyCode:245,charCode:0},
		"VK_ATTN":{keyCode:246,charCode:0},
		"VK_CRSEL":{keyCode:247,charCode:0},
		"VK_EXSEL":{keyCode:248,charCode:0},
		"VK_EREOF":{keyCode:249,charCode:0},
		"VK_PLAY":{keyCode:250,charCode:0},
		"VK_ZOOM":{keyCode:251,charCode:0},
		"VK_PA1":{keyCode:253,charCode:0},
		"VK_WIN_OEM_CLEAR":{keyCode:254,charCode:0}
	},
	"keycodes":{
		3:"VK_CANCEL",
		6:"VK_HELP",
		8:"VK_BACK_SPACE",
		9:"VK_TAB",
		12:"VK_CLEAR",
		13:"VK_RETURN",
		16:"VK_SHIFT",
		17:"VK_CONTROL",
		18:"VK_ALT",
		19:"VK_PAUSE",
		20:"VK_CAPS_LOCK",
		21:"VK_KANA",
		21:"VK_HANGUL",
		22:"VK_EISU",
		23:"VK_JUNJA",
		24:"VK_FINAL",
		25:"VK_HANJA",
		25:"VK_KANJI",
		27:"VK_ESCAPE",
		28:"VK_CONVERT",
		29:"VK_NONCONVERT",
		30:"VK_ACCEPT",
		31:"VK_MODECHANGE",
		32:"VK_SPACE",
		33:"VK_PAGE_UP",
		34:"VK_PAGE_DOWN",
		35:"VK_END",
		36:"VK_HOME",
		37:"VK_LEFT",
		38:"VK_UP",
		39:"VK_RIGHT",
		40:"VK_DOWN",
		41:"VK_SELECT",
		42:"VK_PRINT",
		43:"VK_EXECUTE",
		44:"VK_PRINTSCREEN",
		45:"VK_INSERT",
		46:"VK_DELETE",
		48:"VK_0",
		49:"VK_1",
		50:"VK_2",
		51:"VK_3",
		52:"VK_4",
		53:"VK_5",
		54:"VK_6",
		55:"VK_7",
		56:"VK_8",
		57:"VK_9",
		58:"VK_COLON",
		59:"VK_SEMICOLON",
		60:"VK_LESS_THAN",
		61:"VK_EQUALS",
		62:"VK_GREATER_THAN",
		63:"VK_QUESTION_MARK",
		64:"VK_AT",
		65:"VK_A",
		66:"VK_B",
		67:"VK_C",
		68:"VK_D",
		69:"VK_E",
		70:"VK_F",
		71:"VK_G",
		72:"VK_H",
		73:"VK_I",
		74:"VK_J",
		75:"VK_K",
		76:"VK_L",
		77:"VK_M",
		78:"VK_N",
		79:"VK_O",
		80:"VK_P",
		81:"VK_Q",
		82:"VK_R",
		83:"VK_S",
		84:"VK_T",
		85:"VK_U",
		86:"VK_V",
		87:"VK_W",
		88:"VK_X",
		89:"VK_Y",
		90:"VK_Z",
		91:"VK_WIN",
		93:"VK_CONTEXT_MENU",
		95:"VK_SLEEP",
		96:"VK_NUMPAD0",
		97:"VK_NUMPAD1",
		98:"VK_NUMPAD2",
		99:"VK_NUMPAD3",
		100:"VK_NUMPAD4",
		101:"VK_NUMPAD5",
		102:"VK_NUMPAD6",
		103:"VK_NUMPAD7",
		104:"VK_NUMPAD8",
		105:"VK_NUMPAD9",
		106:"VK_MULTIPLY",
		107:"VK_ADD",
		108:"VK_SEPARATOR",
		109:"VK_SUBTRACT",
		110:"VK_DECIMAL",
		111:"VK_DIVIDE",
		112:"VK_F1",
		113:"VK_F2",
		114:"VK_F3",
		115:"VK_F4",
		116:"VK_F5",
		117:"VK_F6",
		118:"VK_F7",
		119:"VK_F8",
		120:"VK_F9",
		121:"VK_F10",
		122:"VK_F11",
		123:"VK_F12",
		124:"VK_F13",
		125:"VK_F14",
		126:"VK_F15",
		127:"VK_F16",
		128:"VK_F17",
		129:"VK_F18",
		130:"VK_F19",
		131:"VK_F20",
		132:"VK_F21",
		133:"VK_F22",
		134:"VK_F23",
		135:"VK_F24",
		144:"VK_NUM_LOCK",
		145:"VK_SCROLL_LOCK",
		146:"VK_WIN_OEM_FJ_JISHO",
		147:"VK_WIN_OEM_FJ_MASSHOU",
		148:"VK_WIN_OEM_FJ_TOUROKU",
		149:"VK_WIN_OEM_FJ_LOYA",
		150:"VK_WIN_OEM_FJ_ROYA",
		160:"VK_CIRCUMFLEX",
		161:"VK_EXCLAMATION",
		162:"VK_DOUBLE_QUOTE",
		163:"VK_HASH",
		164:"VK_DOLLAR",
		165:"VK_PERCENT",
		166:"VK_AMPERSAND",
		167:"VK_UNDERSCORE",
		168:"VK_OPEN_PAREN",
		169:"VK_CLOSE_PAREN",
		170:"VK_ASTERISK",
		171:"VK_PLUS",
		172:"VK_PIPE",
		173:"VK_HYPHEN_MINUS",
		174:"VK_OPEN_CURLY_BRACKET",
		175:"VK_CLOSE_CURLY_BRACKET",
		176:"VK_TILDE",
		181:"VK_VOLUME_MUTE",
		182:"VK_VOLUME_DOWN",
		183:"VK_VOLUME_UP",
		188:"VK_COMMA",
		190:"VK_PERIOD",
		191:"VK_SLASH",
		192:"VK_BACK_QUOTE",
		219:"VK_OPEN_BRACKET",
		220:"VK_BACK_SLASH",
		221:"VK_CLOSE_BRACKET",
		222:"VK_QUOTE",
		224:"VK_META",
		225:"VK_ALTGR",
		227:"VK_WIN_ICO_HELP",
		228:"VK_WIN_ICO_00",
		230:"VK_WIN_ICO_CLEAR",
		233:"VK_WIN_OEM_RESET",
		234:"VK_WIN_OEM_JUMP",
		235:"VK_WIN_OEM_PA1",
		236:"VK_WIN_OEM_PA2",
		237:"VK_WIN_OEM_PA3",
		238:"VK_WIN_OEM_WSCTRL",
		239:"VK_WIN_OEM_CUSEL",
		240:"VK_WIN_OEM_ATTN",
		241:"VK_WIN_OEM_FINISH",
		242:"VK_WIN_OEM_COPY",
		243:"VK_WIN_OEM_AUTO",
		244:"VK_WIN_OEM_ENLW",
		245:"VK_WIN_OEM_BACKTAB",
		246:"VK_ATTN",
		247:"VK_CRSEL",
		248:"VK_EXSEL",
		249:"VK_EREOF",
		250:"VK_PLAY",
		251:"VK_ZOOM",
		253:"VK_PA1",
		254:"VK_WIN_OEM_CLEAR"
		},
	"keys":{
		"⇥":"VK_TAB",
		"←":"VK_LEFT",
		"↑":"VK_UP",
		"→":"VK_RIGHT",
		"↓":"VK_DOWN",
		"0":"VK_0",
		"1":"VK_1",
		"2":"VK_2",
		"3":"VK_3",
		"4":"VK_4",
		"5":"VK_5",
		"6":"VK_6",
		"7":"VK_7",
		"8":"VK_8",
		"9":"VK_9",
		":":"VK_COLON",
		";":"VK_SEMICOLON",
		"<":"VK_LESS_THAN",
		"=":"VK_EQUALS",
		">":"VK_GREATER_THAN",
		"?":"VK_QUESTION_MARK",
		"@":"VK_AT",
		"A":"VK_A",
		"B":"VK_B",
		"C":"VK_C",
		"D":"VK_D",
		"E":"VK_E",
		"F":"VK_F",
		"G":"VK_G",
		"H":"VK_H",
		"I":"VK_I",
		"J":"VK_J",
		"K":"VK_K",
		"L":"VK_L",
		"M":"VK_M",
		"N":"VK_N",
		"O":"VK_O",
		"P":"VK_P",
		"Q":"VK_Q",
		"R":"VK_R",
		"S":"VK_S",
		"T":"VK_T",
		"U":"VK_U",
		"V":"VK_V",
		"W":"VK_W",
		"X":"VK_X",
		"Y":"VK_Y",
		"Z":"VK_Z",
		"^":"VK_CIRCUMFLEX",
		"!":"VK_EXCLAMATION",
		"#":"VK_HASH",
		"$":"VK_DOLLAR",
		"%":"VK_PERCENT",
		"&":"VK_AMPERSAND",
		"_":"VK_UNDERSCORE",
		"(":"VK_OPEN_PAREN",
		")":"VK_CLOSE_PAREN",
		"*":"VK_ASTERISK",
		"+":"VK_PLUS",
		"|":"VK_PIPE",
		"-":"VK_HYPHEN_MINUS",
		"{":"VK_OPEN_CURLY_BRACKET",
		"}":"VK_CLOSE_CURLY_BRACKET",
		"~":"VK_TILDE",
		",":"VK_COMMA",
		".":"VK_PERIOD",
		"/":"VK_SLASH",
		"`":"VK_BACK_QUOTE",
		"[":"VK_OPEN_BRACKET",
		"]":"VK_CLOSE_BRACKET",
		"'":"VK_QUOTE",
		'"':"VK_DOUBLE_QUOTE",
		"\\":"VK_BACK_SLASH"
	}
};

let GROUPS = exports.GROUPS = {
		"Application": ["key_quitApplication", "key_openHelpMac", "key_openHelp", "key_preferencesCmdMac", "key_hideThisAppCmdMac", "key_hideOtherAppsCmdMac"],
        "Navigation": ["goBackKb", "goBackKb2", "goForwardKb", "goForwardKb2", "goHome", "openFileKb", "key_reload", "key_reload2", "key_forceReload", /*"Ctrl+F5", Ctrl+Shift+R,*/ "key_stop", "key_stop_mac", "focusURLBar", "focusURLBar2"],

        "CurrentPage": [ /*"End", "F6", "Shift+F6",*/ "goHome", "key_viewInfo", "key_viewSource", "printKb", "key_savePage", "key_fullZoomEnlarge", "key_fullZoomReduce", "key_fullZoomReset", "key_fullScreen", "key_fullScreen_old", "key_minimizeWindow", "key_toggleMute","key_switchTextDirection"],

        "Editing": ["key_copy", "key_cut", "key_delete", "key_paste", "key_redo", "key_selectAll", "key_undo"],

        "Search": ["key_find", "key_findAgain", "key_findPrevious", "key_search", "key_search2", "key_findSelection"],

        "WindowsTabs": ["key_close", "key_closeWindow", "key_closeOther", "key_newNavigatorTab", "key_newNavigator", "key_undoCloseTab", "key_undoCloseWindow", "key_selectTab1", "key_selectTab2", "key_selectTab3", "key_selectTab4", "key_selectTab5", "key_selectTab6", "key_selectTab7", "key_selectTab8", "key_selectLastTab", "key_tabview", "key_nextTabGroup", "key_previousTabGroup", "key_prevTab", "key_nextTab","key_showAllTabs"],

        "BookmarksHistory": ["addBookmarkAsKb", "viewBookmarksSidebarKb", "viewBookmarksSidebarWinKb", "manBookmarkKb", "bookmarkAllTabsKb", "key_gotoHistory", "showAllHistoryKb"],

        "Tools": ["key_openDownloads", "key_openAddons", "key_privatebrowsing", "key_sanitize", "key_sanitize_mac"],
        
        "DeveloperTools": ["key_browserConsole",
    "key_webconsole", "key_errorConsole", "key_jsdebugger", "key_inspector",
    "key_styleeditor", "key_jsprofiler", "key_devToolbar", "key_responsiveUI",
    "key_scratchpad", "key_webide","key_devToolboxMenuItem","key_devToolboxMenuItemF12","key_browserToolbox","key_performance","key_netmonitor"],
    	"CustomXUL": []
       };
       
let LABELS = exports.LABELS = {
        "focusURLBar": _("focusURLBar_label"),
        "focusURLBar2": _("focusURLBar2_label"),
        "key_search": _("key_search_label"),
        "key_search2": _("key_search2_label"),
        "key_stop": _("key_stop_label"),
        "key_stop_mac": _("key_stop_mac_label"),
        "key_reload": _("key_reload_label"),
        "key_reload2": _("key_reload2_label"),
        "key_forceReload": _("key_forceReload_label"),
        "key_forceReload2": _("key_forceReload2_label"),
        "goHome": _("goHome_label"),
        "goBackKb": _("goBackKb_label"),
        "goBackKb2": _("goBackKb2_label"),
        "goForwardKb": _("goForwardKb_label"),
        "goForwardKb2": _("goForwardKb2_label"),
        "key_close": _("key_close_label"),
        "key_undoCloseTab": _("key_undoCloseTab_label"),
        "key_undoCloseWindow": _("key_undoCloseWindow_label"),
        "key_toggleAddonBar": _("key_toggleAddonBar_label"),
        "key_findPrevious": _("key_findPrevious_label"),
        "key_selectLastTab": _("key_selectLastTab_label"),
        "key_closeOther": _("key_closeOther_label"),
        "key_prevTab": _("key_prevTab_label"),
        "key_nextTab": _("key_nextTab_label"),
        "key_selectTab1": _("key_selectTab1_label"),
        "key_selectTab2": _("key_selectTab2_label"),
        "key_selectTab3": _("key_selectTab3_label"),
        "key_selectTab4": _("key_selectTab4_label"),
        "key_selectTab5": _("key_selectTab5_label"),
        "key_selectTab6": _("key_selectTab6_label"),
        "key_selectTab7": _("key_selectTab7_label"),
        "key_selectTab8": _("key_selectTab8_label"),
        "key_tabview": _("key_tabview_label"),
        "key_nextTabGroup": _("key_nextTabGroup_label"),
        "key_previousTabGroup": _("key_previousTabGroup_label"),
        "key_toggleMute": _("key_toggleMute_label"),
        "key_sanitize_mac": _("key_sanitize_mac_label"),
        "key_devToolboxMenuItemF12": _("key_devToolboxMenuItemF12_label"),
        "key_devToolboxMenuItem": _("key_devToolboxMenuItem_label"),
        "key_fullScreen_old": _("key_fullScreen_old_label"),
        "key_minimizeWindow": _("key_minimizeWindow_label"),
		"key_switchTextDirection": _("key_switchTextDirection_label"),
		"key_toggleMute": _("key_toggleMute_label"),
		"key_findSelection": _("key_findSelection_label"),		
		"key_webide": _("key_webide_label"),
		"focusChatBar": _("focusChatBar_label"),
        "key_firebug_toggleBreakOn": _("key_firebug_toggleBreakOn_label"),
        "key_firebug_detachFirebug": _("key_firebug_detachFirebug_label"),
        "key_firebug_closeFirebug": _("key_firebug_closeFirebug_label"),
        "key_firebug_focusCommandLine": _("key_firebug_focusCommandLine_label"),
        "key_firebug_toggleInspecting": _("key_firebug_toggleInspecting_label"),
        "key_foxyproxyquickadd": _("key_foxyproxyquickadd_label"),
        "key_changeproxy": _("key_changeproxy_label"),
        "secureLoginShortcut": _("secureLoginShortcut_label")
    };